"""
Django settings for kairos_project project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

BASE_DIR = Path(__file__).resolve().parent.parent

# =================================================
# == CORE SETTINGS                               ==
# =================================================
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# Hosts: siempre incluye localhost para dev, agrega tu dominio Oracle via env
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Agregar hosts extra desde .env (separados por coma)
# Ejemplo: ALLOWED_HOSTS_EXTRA=kairos.example.com,150.136.xx.xx
for host in os.getenv('ALLOWED_HOSTS_EXTRA', '').split(','):
    host = host.strip()
    if host:
        ALLOWED_HOSTS.append(host)

NGROK_HOSTNAME = os.getenv('NGROK_HOSTNAME')
if NGROK_HOSTNAME:
    ALLOWED_HOSTS.append(NGROK_HOSTNAME)

# CSRF: en producción, necesitas declarar los orígenes confiables
CSRF_TRUSTED_ORIGINS = []
for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(','):
    origin = origin.strip()
    if origin:
        CSRF_TRUSTED_ORIGINS.append(origin)
if NGROK_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{NGROK_HOSTNAME}')

# Security headers para producción
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tu_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tu_app.middleware.CanvasTokenRefreshMiddleware',  # Refrescador automático de tokens
]

ROOT_URLCONF = 'kairos_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kairos_project.wsgi.application'


# =================================================
# == DATABASE                                    ==
# =================================================
# En producción usa PostgreSQL via DATABASE_URL
# Formato: postgres://USER:PASSWORD@HOST:PORT/DBNAME
# En desarrollo usa SQLite si DATABASE_URL no está configurada

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =================================================
# == LOGGING CONFIGURATION                       ==
# =================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'tu_app': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# =================================================
# == CONFIGURACIÓN DE CANVAS OAUTH 2.0           ==
# =================================================
# Esta debe ser la URL de tu instancia de Canvas. ¡AJÚSTALA!
# Ejemplo: "https://canvas.instructure.com"
CANVAS_BASE_URL = os.getenv('CANVAS_BASE_URL')

# Cargar credenciales desde variables de entorno para mayor seguridad.
CANVAS_CLIENT_ID = os.getenv('CANVAS_CLIENT_ID')

CANVAS_CLIENT_SECRET = os.getenv('CANVAS_CLIENT_SECRET')

# La URI de redirección también debe ser configurable.
# Ejemplo: "https://<tu-url-ngrok>.ngrok-free.dev/callback"
CANVAS_REDIRECT_URI = os.getenv('CANVAS_REDIRECT_URI')