# Generated by Django 6.0.2 on 2026-02-04 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('canvas_user_id', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('scopes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canvas Token',
                'verbose_name_plural': 'Canvas Tokens',
            },
        ),
    ]
