# Generated by Django 6.0.2 on 2026-02-04 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canvastoken',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Maestro'), ('admin', 'Administrador'), ('unknown', 'Desconocido')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_course_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('enrollment_role', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'canvas_course_id')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_module_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('position', models.IntegerField()),
                ('is_locked', models.BooleanField(default=False)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tu_app.course')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('course', 'canvas_module_id')},
            },
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_item_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('item_type', models.CharField(choices=[('File', 'Archivo'), ('Page', 'Página'), ('Assignment', 'Tarea'), ('Quiz', 'Cuestionario'), ('Discussion', 'Discusión'), ('ExternalUrl', 'Enlace Externo'), ('ExternalTool', 'Herramienta Externa'), ('SubHeader', 'Encabezado'), ('Other', 'Otro')], max_length=50)),
                ('position', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('content_id', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('completion_requirement', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tu_app.module')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('module', 'canvas_item_id')},
            },
        ),
    ]
