# Generated by Django 6.0.2 on 2026-02-16 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_app', '0002_canvastoken_role_course_module_moduleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando'), ('completed', 'Completado'), ('failed', 'Error')], default='pending', max_length=20)),
                ('vector_db_path', models.CharField(blank=True, max_length=500)),
                ('total_items_processed', models.IntegerField(default=0)),
                ('embedding_model', models.CharField(default='sentence-transformers/all-MiniLM-L6-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='tu_app.module')),
            ],
            options={
                'verbose_name': 'Module Analysis',
                'verbose_name_plural': 'Module Analyses',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('ai', 'IA')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(default='deepseek', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tu_app.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tu_app.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'course', '-created_at'], name='tu_app_chat_user_id_47f3aa_idx')],
            },
        ),
    ]
