# Generated by Django 6.0.2 on 2026-02-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_app', '0003_moduleanalysis_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_data', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(default='sentence-transformers/all-MiniLM-L6-v2', max_length=100)),
                ('document_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='tu_app.module')),
            ],
            options={
                'verbose_name': 'Module Embedding',
                'verbose_name_plural': 'Module Embeddings',
            },
        ),
    ]
