# Generated by Django 6.0.2 on 2026-02-23 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_app', '0004_moduleembedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_user_id', models.IntegerField(db_index=True, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('first_login_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_logins', models.PositiveIntegerField(default=1)),
                ('total_questions_asked', models.PositiveIntegerField(default=0)),
                ('total_modules_studied', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to='tu_app.studentprofile')),
            ],
            options={
                'verbose_name': 'Login Record',
                'verbose_name_plural': 'Login Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['canvas_user_id'], name='tu_app_stud_canvas__c2d114_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['last_login_at'], name='tu_app_stud_last_lo_7533a7_idx'),
        ),
        migrations.AddIndex(
            model_name='loginrecord',
            index=models.Index(fields=['student_profile', '-timestamp'], name='tu_app_logi_student_75b1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='loginrecord',
            index=models.Index(fields=['-timestamp'], name='tu_app_logi_timesta_fc3e84_idx'),
        ),
    ]
