# Generated by Django 6.0.2 on 2026-02-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_app', '0005_studentprofile_loginrecord_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='tu_app_stud_canvas__c2d114_idx',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='canvas_user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
